Adds button and header styling
rangle/bridge-lcbo-app-cohort-2 pull request #20
Opened 2017-07-27 20:19 UTC by jprittie

Hello... this feels quite hacky compared to what Jocelyn did and I won't be offended if you want a major overhaul. I'm thinking I probably should have used flexbox in the header?

We can also probably find a better background image. Normally I have good luck with unsplash, but couldn't find anything that said "liquor store." I also added a red svg circle we can use with the shopping cart. It's just hanging out in the img folder... I haven't imported or styled it yet.

Jen!! I don't know how to add a comment directly under yours, so I'm editing. This isn't hacky AT ALL. It's good. And you can definitely have flexbox in the header...or not. It's whatever style you like and what works for you. Good work. -JJ

2017-07-27 23:07 UTC, jocelynjeffrey commented on src/App.css
> +  border-image: none;
you can take this line out - it's not doing anything here

2017-07-27 23:11 UTC, jocelynjeffrey commented on src/App.css
> +  height: 40px;
your max-width is less than your min-width here; your min will cancel out your max. You can probably ditch the max-width

2017-07-27 23:19 UTC, jocelynjeffrey commented on src/App.css
> +*:-moz-placeholder {
I think this syntax is deprecated. You should be okay using only ::moz-placeholder from above

2017-07-27 23:23 UTC, jocelynjeffrey commented on src/components/Header/Header.css
> +  padding-top: 100px;
you can combine these with shorthand! `padding: 100px 0;` The shorthand takes up to 4 options, one for each side (set clockwise, from the top). If you only give 2, it uses the 1st as top and bottom and the 2nd as left and right.

2017-07-27 23:24 UTC, jocelynjeffrey commented on src/components/SearchBar/SearchBar.css
> +  padding: 0 0 0 20px;
nice!

2017-07-27 23:24 UTC, jocelynjeffrey commented on src/components/SearchBar/SearchBar.css
> +  min-width: 80px;
I don't think you ever hit this size, you probably can remove this.

2017-07-27 23:25 UTC, jocelynjeffrey commented on src/components/SearchBar/SearchBar.css
> +  border-image: none;
can remove

2017-07-27 23:25 UTC, jocelynjeffrey commented on src/components/SearchBar/SearchBar.css
> +  border-image: none;
can remove

2017-07-27 23:27 UTC, jocelynjeffrey reviewed
I left a few comments for updates, but great work. It looks so good!

2017-07-27 23:35 UTC, astr0-4 requested changes
this looks amazing @jprittie!!! 
just some small fixes and it's good to go

2017-07-27 23:35 UTC, astr0-4 commented on src/App.css
> +  border-color: none;
I think border-style, image, and color all have default values of none so you could remove these

2017-07-27 23:35 UTC, astr0-4 commented on src/components/Header/Header.js
> +  backgroundImage: 'url(' + cheers  + ')',
you could use the template literals style to write this: \` url(${cheers}) \`

2017-07-27 23:35 UTC, astr0-4 commented on src/components/SearchBar/SearchBar.css
> +}
I think here as well you can remove border-style, image, and color

2017-07-27 23:35 UTC, astr0-4 commented on src/App.css
> +  min-width: 100px;
here your `max-width` is smaller than your `min-width`

2017-07-27 23:37 UTC, jprittie commented on src/App.css
> +button {
Comment

2017-07-28 00:08 UTC, jocelynjeffrey approved these changes

2017-07-28 00:10 UTC, astr0-4 approved these changes

2017-07-28 00:11 UTC, merged