Adds Cart button badge to correspond to the items in the wishlist
rangle/bridge-lcbo-app-cohort-2 pull request #22
Opened 2017-07-29 01:05 UTC by astr0-4

## Screenshots
![screen shot 2017-07-28 at 9 00 00 pm](https://user-images.githubusercontent.com/6060764/28740829-3936ba82-73d8-11e7-8de4-1114aa221768.png)
![screen shot 2017-07-28 at 9 00 23 pm](https://user-images.githubusercontent.com/6060764/28740830-3aa795ee-73d8-11e7-9fed-4aa6aac4a8ff.png)

2017-07-29 20:26 UTC, ghost approved these changes
Great Work Alex! LGTM!

2017-07-29 20:54 UTC, jocelynjeffrey requested changes

2017-07-29 20:54 UTC, jocelynjeffrey commented on src/components/CartButton/CartButton.css
> +	margin-top: -3px;
You can shorten this code by changing the top and right values to -3px and removing the margin-right and margin-top lines

2017-07-29 20:54 UTC, jocelynjeffrey commented on src/components/CartButton/CartButton.css
> +	padding-right: 2px;
you can use shorthand here: `padding: 0 2px;`

2017-07-29 20:54 UTC, jocelynjeffrey commented on src/components/CartButton/CartButton.css
> +	flex-direction: row;
since you're absolutely positioning the indicator button, you probably don't need `display: flex` or `flex-direction` here

2017-07-29 20:54 UTC, jocelynjeffrey commented on src/components/CartButton/CartButton.css
> +	vertical-align: middle;
vertical-align doesn't work here so you can remove it.

2017-07-29 20:54 UTC, jocelynjeffrey commented on src/components/CartButton/CartButton.css
> +	background-image: '../../img/shopping_cart.svg';
you've also got this in the CartButton.js file, so you can remove this here (I don't think it'll work without the url('path') syntax)

2017-07-29 20:54 UTC, jocelynjeffrey commented on src/components/CartButton/CartButton.js
> +}
since cartImageStyle is styling, you could move it into the `.cart-wrapper` css styles. That way we'll have all of our our styles in one spot

2017-07-30 12:57 UTC, astr0-4 commented
@jocelynjeffrey fixes made! Thanks for the comments 😃

2017-07-30 17:08 UTC, jocelynjeffrey commented
Awesome work Alex. Merging!

2017-07-30 17:08 UTC, jocelynjeffrey approved these changes

2017-07-30 18:03 UTC, merged