Adds tests for header reducer
rangle/bridge-lcbo-app-cohort-2 pull request #24
Opened 2017-07-30 21:23 UTC by astr0-4

Adds prettier-eslint as a dev dependency 
https://www.npmjs.com/package/prettier-eslint

2017-07-31 00:12 UTC, jocelynjeffrey requested changes
hey @astr0-4 - the tests are working but something with the reducer isn't working. The input says [object, object] (screenshot included)

<img width="467" alt="screen shot 2017-07-30 at 8 07 46 pm" src="https://user-images.githubusercontent.com/5385445/28758292-66b05d74-7563-11e7-9b9a-8d21e1ccf13a.png">

2017-07-31 01:47 UTC, astr0-4 commented
good catch @jocelynjeffrey!!! It should be fixed now

2017-07-31 14:51 UTC, jprittie approved these changes
Just wondering if we should put the test for a component or reducer inside the folder where the component/reducer lives.

2017-07-31 14:59 UTC, jprittie reviewed
If I do npm run test a warning comes up for the reducer test.

2017-07-31 14:59 UTC, jprittie commented on src/tests/reducers/header.reducer.test.js
> +  HEADER_ACTIONS,
When I run the tests I get 'HEADER_ACTIONS is defined but never used.

2017-08-01 11:56 UTC, jocelynjeffrey approved these changes

2017-08-01 11:56 UTC, jocelynjeffrey commented on src/tests/reducers/header.reducer.test.js
> +  HEADER_ACTIONS,
@jprittie @astr0-4 I see this warning too - if we're not using HEADER_ACTIONS let's delete it and we're good to go!

2017-08-01 12:23 UTC, merged