Adds map markers, decreases zoom
rangle/bridge-lcbo-app-cohort-2 pull request #49
Opened 2017-08-14 15:43 UTC by jprittie

2017-08-14 16:01 UTC, ghost approved these changes
Great work Jen!

2017-08-14 17:09 UTC, jocelynjeffrey approved these changes
Very cool, @jprittie

2017-08-15 02:54 UTC, astr0-4 requested changes

2017-08-15 02:54 UTC, astr0-4 commented on src/containers/StoreFinder.container.js
> +		<LocationMap {...props] />
@jprittie I think the `]` instead of `}` is the reason your build is failing

2017-08-15 03:06 UTC, merged