Feature/locate user
rangle/bridge-lcbo-app-cohort-2 pull request #52
Opened 2017-08-18 00:16 UTC by Prtfw

- user location now hooked up to state....
- query now uses the user location as lat/lng

2017-08-18 12:53 UTC, Prtfw commented
them tests be passing!!! y'all good to review now... : )

2017-08-19 14:59 UTC, astr0-4 requested changes
This is awesome @Prtfw!! Some tweaks can be made, but it's great to see the map going! 🗺  🗺

2017-08-19 14:59 UTC, astr0-4 commented on src/App.js
> +  }
do we still need this here?

2017-08-19 14:59 UTC, astr0-4 commented on src/components/LocationMap/LocationMap.js
> +      // this.mapLib.panTo(this.props.latLng)
do we still need to actually pan to the user's location?

2017-08-19 14:59 UTC, astr0-4 commented on src/redux/actions/storeLocation.actions.js
> +export const getStoresByProductIDs = payload => ({
I like the name ids better, it's more descriptive and consistent with what we did below. Maybe we could call it `productIDs` instead of payload?

2017-08-19 14:59 UTC, astr0-4 commented on src/redux/epics/getStoreLocations.epic.js
> +} from "../actions/storeLocation.actions";
this should be formatted with prettier

2017-08-19 14:59 UTC, astr0-4 commented on src/redux/epics/getStoreLocations.epic.js
> +const productIDs = (ids=[]) => ids.join(",");
semi-colons! 🙅

2017-08-19 14:59 UTC, astr0-4 commented on src/redux/epics/getStoreLocations.epic.js
> +          .lat}&lon=${action.payload.latLng.lng}&access_key=${LCBO_API_KEY}`,
yesssss this is awesome!!!!

2017-08-19 14:59 UTC, astr0-4 commented on src/redux/epics/getStoreLocations.epic.js
> +    navigator.geolocation.getCurrentPosition(function(position) {
can we do this with ES6 function syntax?

2017-08-19 14:59 UTC, astr0-4 commented on src/redux/epics/getStoreLocations.epic.js
> +      resolve({ lat: position.coords.latitude, lng: position.coords.longitude });
nice with the promises!! 👍 💯 🎉

2017-08-19 14:59 UTC, astr0-4 commented on src/redux/reducers/index.js
> +
remove this space

2017-08-19 14:59 UTC, astr0-4 commented on src/redux/reducers/storeLocation.reducer.js
> +  latLng: { lat: 43.6532, lng: -79.3832 }, // same as TOR_LAT_LNG
👍

2017-08-19 14:59 UTC, astr0-4 commented on src/redux/reducers/storeLocation.reducer.js
> +      })
remove the `console.log`

2017-08-19 14:59 UTC, astr0-4 commented on src/redux/reducers/storeLocation.reducer.js
> +export default storeLocationReducer;
no semi colons!

2017-08-19 14:59 UTC, astr0-4 commented on src/tests/epics/getStoreLocations.epic.test.js
> +const action$ = ActionsObservable.of(getStoresByProductIDs({ids:[1, 2, 3], latLng: {lat: 0, lng: 0}}))
👏  👏

2017-08-19 15:08 UTC, Prtfw commented on src/redux/actions/storeLocation.actions.js
> +export const getStoresByProductIDs = payload => ({
thanks for the review... I will take care of the fix except maybe this one... rationale is:
... the payload is no longer a simple list of ids. It actually contains the current latLng as well ...  with shape payload = {ids: [id1, id2,....], latLng: {lat: 999, lng: 0000}}.

2017-08-19 15:14 UTC, astr0-4 commented on src/redux/actions/storeLocation.actions.js
> +export const getStoresByProductIDs = payload => ({
oooh right, I see. ok I'm good with payload then 👍

2017-08-19 17:32 UTC, jocelynjeffrey reviewed
Very cool @Prtfw ! Left a few comments, let me know what you think.

2017-08-19 17:32 UTC, jocelynjeffrey commented on src/components/LocationMap/LocationMap.js
> +      // this.mapLib.panTo(this.props.latLng)
Agreed, I think we need this working as part of this story

2017-08-19 17:32 UTC, jocelynjeffrey commented on src/redux/epics/getStoreLocations.epic.js
> +          .lat}&lon=${action.payload.latLng.lng}&access_key=${LCBO_API_KEY}`,
agreed! 🎉

2017-08-19 17:32 UTC, jocelynjeffrey commented on src/redux/epics/getStoreLocations.epic.js
> +      resolve({ lat: position.coords.latitude, lng: position.coords.longitude });
I think we should handle reject here as well (even if we just console.log an error message for us to use while we're developing)

2017-08-19 18:21 UTC, ghost approved these changes
Looks good!

2017-08-19 18:22 UTC, ghost reviewed
Looks good!

2017-08-19 21:20 UTC, astr0-4 commented on src/components/LocationMap/LocationMap.js
> +      // this.mapLib.panTo(this.props.latLng)
I'm ok with getting this merged in and doing the panning to the user's location in another PR. We could create another task for finishing off the map, which could include panning and also letting the user click on a marker and seeing the store details (I assume we are going to include that?)

2017-08-19 22:24 UTC, Prtfw commented
@astr0-4 @jocelynjeffrey @holdersimone thanks for the code review... made changes as per comments. squash n merging. Cheers!

2017-08-19 22:24 UTC, merged