[FEATURE] Styling store list item components
rangle/bridge-lcbo-app-cohort-2 pull request #53
Opened 2017-08-18 01:30 UTC by astr0-4

* adjusts map and store list container

2017-08-19 18:21 UTC, ghost approved these changes
LGTM!

2017-08-20 00:10 UTC, jprittie requested changes

2017-08-20 00:10 UTC, jprittie commented on src/components/StoresList/StoresList.js
> +                <h2>{store.name}</h2>
Hello... I am getting a console error here. It says "Warning: validateDOMNesting(...): 'h2' cannot appear as a descendant of 'p'.

2017-08-20 13:19 UTC, astr0-4 commented on src/components/StoresList/StoresList.js
> +                <h2>{store.name}</h2>
good catch @jprittie! I've updated it now.

2017-08-20 13:56 UTC, Prtfw commented
👍  LGTM Alex! great css organization

2017-08-20 13:56 UTC, Prtfw approved these changes

2017-08-20 22:55 UTC, merged