added dynamic hours based on today's day of the week
rangle/bridge-lcbo-app-cohort-2 pull request #54
Opened 2017-08-21 00:40 UTC by jocelynjeffrey

2017-08-21 11:26 UTC, jprittie approved these changes
Nice!

2017-08-21 13:51 UTC, astr0-4 commented on src/components/StoresList/StoresList.js
> +  }
It's not a big deal since I'm sure we will only be using this here, but what are your thoughts on putting these in a "utilities" or "helpers" file?

2017-08-21 13:51 UTC, astr0-4 commented on src/components/StoresList/StoresList.js
> +
it would be a bit cleaner to do:
`const weekday = ["sunday", "monday", "tuesday",...]`

2017-08-21 14:32 UTC, Prtfw commented
Looks pretty good... although there is a package I wonder if we want to consider using momentjs which has a bunch of existing functions for time/timezone/time parsing and formatting (which IMO is one of the worst things to deal with as a dev... 2nd only to cors).
I am too lazy to write and write tests for any time related code myself : )
https://momentjs.com/docs/
this will also contribute towards Alex's helper file suggestion : )
Just me 2 cents!

2017-08-21 17:29 UTC, astr0-4 commented
@Prtfw momentjs looks amazing 👀 ! But since we are only dealing with time in this one place, we prob don't need it for now. Going to make a note of this library for future though...

2017-08-21 21:56 UTC, jocelynjeffrey commented on src/components/StoresList/StoresList.js
> +
yeah, that's a good call. I'll update!

2017-08-21 22:05 UTC, jocelynjeffrey commented on src/components/StoresList/StoresList.js
> +  }
Yeah, let's make our components as clean as possible. Good idea!

2017-08-21 22:09 UTC, jocelynjeffrey commented
code updated! @Prtfw, good call on the moment.js library. It's definitely something that would speed up the process! I haven't added in moment.js this time - I agree with @astr0-4 that it seems like we probably don't need it if we're just dealing with time in this component. But if someone on the team wants to give it a go (or if we find another place we need date/times in our app) we should consider adding it in.

2017-08-21 22:50 UTC, astr0-4 commented
![screen shot 2017-08-21 at 6 48 56 pm](https://user-images.githubusercontent.com/6060764/29541351-7cb8e39e-86a1-11e7-8f1f-28b183ed188d.png)
@jocelynjeffrey I'm seeing something weird for 30min items...
I think we need some more spacing between the hours label and the bottom border.

2017-08-21 22:51 UTC, astr0-4 requested changes
![screen shot 2017-08-21 at 6 48 56 pm](https://user-images.githubusercontent.com/6060764/29541351-7cb8e39e-86a1-11e7-8f1f-28b183ed188d.png)
@jocelynjeffrey I'm seeing something weird for 30min items...
Also I think we need some more spacing between the hours label and the bottom border.

2017-08-22 00:58 UTC, ghost reviewed
This looks great! I like the idea of more padding between the hours and the dividing line.
I also like the idea of using the helper file.

2017-08-22 22:43 UTC, astr0-4 approved these changes
Nice!! 💯

2017-08-22 22:44 UTC, merged